apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino
  labels:
    app: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino
  template:
    metadata:
      labels:
        app: trino
    spec:
      containers:
      - name: trino
        image: trinodb/trino
        ports:
        - containerPort: 8080